### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by vkuehn** [notkarol/derplearning#22]
Hi,

I woulld like to start with camera calibration but you are looking for circles

        ret, corners = cv2.findCirclesGrid(
            gray_frame, pattern_shape, flags=cv2.CALIB_CB_ASYMMETRIC_GRID
        )

which fails for me, According to the docs it should be cv2.findChessboardCorners no ?

**Comment by John-Ellis** [comment]
Oh, sorry, I'll update the docs, we changed it to the hex circles pattern to get more reliable calibration.

**Comment by vkuehn** [comment]
ok thanks.

Kudos for the Links !
